### ISSUE TITLE
Migrate add_to_log to use new logging system

### ISSUE THREAD

**Issue by rlorenzo** [lsuits/quickmail#180]
There is an add_to_log call that is using the old logging system. We are submitting a patch to update it.

**Comment by rlorenzo** [comment]
Patch submitted by one of our students. Please review and let us know what you think.

**Comment by nadavkav** [comment]
Looks good. Please see if you can integrate.

**Comment by elliott2081** [comment]
looks good. I will test it today on my dev server. Can you make it a pull request?
